### ISSUE TITLE
parameters.cfg

### ISSUE THREAD

**Issue by syy-mudong** [gnomeCreative/HYBIRD#4]
Hello,@gnomeCreative
I am currently studying LBM and I am very interested in LBM-DEM. I would like to learn your code to deepen my understanding of LBM-DEM. I have seen a similar code before, but the results of running it are not very stable. If possible, My email address is s13857678419@gmail.com ,could you please share your parameters.cfg? I would greatly appreciate to it !!!
Best wishes
Shen

**Comment by gnomeCreative** [comment]
Hello,
I added a manual, with a few example. That could be useful for you, it contains several benchmarks with the configuration files. Hope this helps!
Alessandro

**Comment by syy-mudong** [comment]
hi,@gnomeCreative
Thank you very much for your help. I will try it.
Best wishes
Shen
